version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '123456'
  # n8n:
  #   container_name: pihole
  #   image: n8nio/n8n:latest
  #   ports:
  #     - "5678:5678/tcp"
